### ISSUE TITLE
Get Error when the input is 1 image.

### ISSUE THREAD

**Issue by Frank-Dz** [bharat-b7/MultiGarmentNetwork#28] opened 2020-04-18 10:29 UTC
Hi~
I am currently using the default test_data.pkl which includes 8 images.
To use 1 image, I set:
```
NUM, IMG_SIZE, FACE = 1, 720, False
``` 
And according to [https://github.com/bharat-b7/MultiGarmentNetwork/issues/19](https://github.com/bharat-b7/MultiGarmentNetwork/issues/19), I also added:
```
    dat['rendered'] = dat['rendered'][:, :, :, :, : NUM]  # new added to make the frame number compatible with NUM.
```
This works well when NUM is 2.
But when NUM is 1, I got:
```
WARNING:tensorflow:From /home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/ops/resource_variable_ops.py:642: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "/home/frank/PycharmProjects/MultiGarmentNetwork/test_network.py", line 198, in <module>
    pred = get_results(m, dat)
  File "/home/frank/PycharmProjects/MultiGarmentNetwork/test_network.py", line 55, in get_results
    out = m([images, vertex_label, J_2d])
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 592, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/frank/PycharmProjects/MultiGarmentNetwork/network/base_network.py", line 309, in call
    latent_code_offset = self.avg([q[0] for q in lat_codes])
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 151, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/keras/layers/merge.py", line 94, in build
    'Got ' + str(len(input_shape)) + ' inputs.')
ValueError: A merge layer should be called on a list of at least 2 inputs. Got 1 inputs.

Process finished with exit code 1
```

Plus, I am running on a single GPU and set ```config.train.batch_size = 1```. 
To avoid TF resources exhausted, I added ```dat = {k: v[:config.train.batch_size] for k, v in dat.items()}  # added this to slice the data``` below
```
dat = pkl.load(open('assets/test_data.pkl', "rb"), encoding="latin1")  
```

In a word, the ```dat = pkl.load(open('assets/test_data.pkl', "rb"), encoding="latin1")  ``` now is:
```
dat = pkl.load(open('assets/test_data.pkl', "rb"), encoding="latin1")  # added this encoding stuff for Python3
dat = {k: v[:config.train.batch_size] for k, v in dat.items()}  # added this to slice the data
dat['rendered'] = dat['rendered'][:, :, :, :, : NUM]  # new added to make the frame number compatible with NUM.
```

**Comment by Frank-Dz** [comment] 2020-04-18 10:35
I also checked NUM=3,4,5,6,7,8.  It works well for me, but when NUM = 1 I met the problem above.

Thanks in advance.

**Comment by andrewjong** [comment] 2020-04-23 02:41
I can confirm, I too get the error
`ValueError: A merge layer should be called on a list of at least 2 inputs. Got 1 inputs.`

Seems the Keras Average() layer doesn't like working on the single image.

**Comment by andrewjong** [comment] 2020-04-23 03:08
@bharat-b7 can MGN successfully extract 3D from just a single image?

**Comment by andrewjong** [comment] 2020-04-23 03:22
I managed to get around it by making the following change on [line 309-310 of base_network.py](https://github.com/bharat-b7/MultiGarmentNetwork/blob/fbd22e4012ee835abe1210fcf1a5ae2fae145ed5/network/base_network.py#L309):
```python
latent_code_offset = self.avg([q[0] for q in lat_codes]) if (len(lat_codes) > 1 ) else lat_codes[0][0]
latent_code_betas = self.avg([q[1] for q in lat_codes]) if (len(lat_codes) > 1 ) else lat_codes[0][1]
```
Inference runs perfectly with this change!

**Comment by Frank-Dz** [comment] 2020-04-25 01:09
Thank! It works well for me!

Best,
Frank

**Comment by andrewjong** [comment] 2020-04-25 02:36
Maybe this issue should not be closed, but rather merged into the main branch. Being able to extract on 1 image seems to be part of the paper's claims.

**Comment by Frank-Dz** [comment] 2020-04-26 09:24
I reopen it, since "Being able to extract on 1 image seems to be part of the paper's claims."

**Comment by neonb88** [comment] 2020-05-06 08:42
For those interested (ie. @andrewjong), there are many other papers & github repos that use only 1 image, ie. https://github.com/akanazawa/hmr, https://github.com/mohomran/neural_body_fitting, https://github.com/vchoutas/smplify-x.  And any "related works" listed in their publications probably reference more publicly available code

**Comment by bharat-b7** [comment] 2020-05-06 17:02
The above works only fit SMPL to image. There is no detailed geometry.
A much closer work will be: https://github.com/thmoa/octopus but it has the same strategy as MGN for dealing with a single image.

**Comment by PRAKHAR-bit** [comment] 2020-05-14 07:47
@Frank-Dz 
Hi Frank, I would be extremely grateful that if the textures on the clothes automatically came by running dress_smpl.py or you had to run some extra code for it. As because I am running it and the texture is not coming. only clothes are fit( I am using the dataset provided in the code itsef)

**Comment by PRAKHAR-bit** [comment] 2020-05-14 07:50
@neonb88 
Please suggest .
"Hi Frank, I would be extremely grateful that if the textures on the clothes automatically came by running dress_smpl.py or you had to run some extra code for it. As because I am running it and the texture is not coming. only clothes are fit( I am using the dataset provided in the code itsef) "

**Comment by PRAKHAR-bit** [comment] 2020-05-14 07:51
@bharat-b7 Please sir
"
"Hi Frank, I would be extremely grateful that if the textures on the clothes automatically came by running dress_smpl.py or you had to run some extra code for it. As because I am running it and the texture is not coming. only clothes are fit( I am using the dataset provided in the code itsef) "

**Comment by Frank-Dz** [comment] 2020-05-14 07:53
> @neonb88
> Please suggest .
> "Hi Frank, I would be extremely grateful that if the textures on the clothes automatically came by running dress_smpl.py or you had to run some extra code for it. As because I am running it and the texture is not coming. only clothes are fit( I am using the dataset provided in the code itsef) "

Hi~ If you wanna use the texture, please pay attention to ``` garment_unposed.set_texture_image(garment_tex) ``` in dress_SMPL.py
The texture image is named 'multi_tex.jpg' in the 1st dataset.

**Comment by PRAKHAR-bit** [comment] 2020-05-14 07:56
@Frank-Dz 
I am running on a windows system after creating the python bindings required for running the code i created an .obj file annd .mtl file. But when i render it using .obj viewers (cloth fit perfectly) but texture is not their

**Comment by Frank-Dz** [comment] 2020-05-15 13:06
> For those interested (ie. @andrewjong), there are many other papers & github repos that use only 1 image, ie. https://github.com/akanazawa/hmr, https://github.com/mohomran/neural_body_fitting, https://github.com/vchoutas/smplify-x. And any "related works" listed in their publications probably reference more publicly available code

Hi~@neonb88 I sent you an email. But looks like it was blocked. Could you please have a check?
Thanks in advance!

Best,
Frank

**Closed as completed** 2023-01-16 02:12 UTC
